[book]
authors = ["Nicolas Stalder"]
language = "en"
multilingual = false
src = "src"
title = "Salty"

[output.html]
git-repository-url = "https://github.com/nickray/salty"
git-repository-icon = "fa-github"
