[package]
name = "salty"
version = "0.1.0-alpha.1"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
description = "Small, sweet, swift Ed25519 signatures for microcontrollers"
homepage = "https://salty.rs"
repository = "https://github.com/nickray/salty"
license = "Apache-2.0 OR MIT"
readme = "README.md"
keywords = ["no-std", "NaCl", "Ed25519", "cryptography", "signatures"]

[dependencies]
cosey = { version = "0.1.0-alpha.0", optional = true }
subtle = { version = "2.2", default-features = false }

[dev-dependencies]
hex-literal = "0.2.1"

[features]
slow-motion = []
cose = ["cosey"]
